name: Lint/Test
run-name: Lint/Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    uses: jhae-de/jhae-de/.github/workflows/lint-simple-project.yaml@main

  test:
    name: Test
    uses: jhae-de/jhae-de/.github/workflows/test-simple-project.yaml@main
    with:
      test-script: 'test'
